#!/usr/bin/env bash
cd ./webapp
sudo docker-compose up &
#sudo docker ps
#sudo docker-compose ps 
#echo $(sudo docker network inspect api_default | grep Gateway | grep -o -E '[0-9\.]+')
#curl 172.18.0.1
#curl 172.18.0.1/index.php
#curl 172.18.0.1/connect.php
